### ISSUE TITLE
Filesystem watcher errors

### ISSUE THREAD

**Issue by RudderDuck** [Start9Labs/syncthing-wrapper#17]
After adding a folder to sync the following box appears about Filesystem Watcher Errors:

![Screenshot 2022-07-23 at 19-02-18 syncthing embassy Syncthing](https://user-images.githubusercontent.com/10198193/180615315-6d043cc6-cfb6-4595-8e59-7aedf6275768.png)

I followed the instructions on the following page on the client (linux) and set the watches to 204800:

https://docs.syncthing.net/users/faq.html#inotify-limits

This did not remove the error message so I suspect it is a setting that needs to be set within Embassy OS. The app does synchronize but it is unclear whether this affects proper operation.

**Comment by Blu-J** [comment]
`sudo sysctl -w fs.inotify.max_user_watches=1048576`
Apparently I have to run this outside the docker instance, and before it was.

To fix this, I'm going to have to have changes to the main system, will talk with the team about embassy os changes, and link any related issues.

![image](https://user-images.githubusercontent.com/2364004/180910510-de41f445-0a18-4000-af98-7879d38ddd08.png)
