### ISSUE TITLE
Need to upgrade to Syncthing v1.22 Service 

### ISSUE THREAD

**Issue by rrandor1** [Start9Labs/syncthing-wrapper#24]
The Syncthing client app V1.20 does not run on my Mac OS 12.6    
V1.22 Client app does run. So I need to upgrade the Syncthing Server app to the same version.  On this site I find the various installs for this version.
https://github.com/syncthing/syncthing/releases/tag/v1.22.0
It looks like the right install for RaspPi V4 B which is an ARM 64bit processor would be
 syncthing-freebsd-arm64-v1.22.0.tar.gz 
If it is Embassy One-ready, how would I install it?

**Comment by Blu-J** [comment]
Going to update to the latest, but it will be after the next version of the os which is close.

**Comment by rrandor1** [comment]
<div></div><div>Going to update to the latest, but it will be after the next version of the os which is close.
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/Start9Labs/syncthing-wrapper/issues/24#issuecomment-1289308280
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by gStart9** [comment]
https://github.com/Start9Labs/syncthing-wrapper/releases/tag/v1.22.1.1

^ released, closing
