### ISSUE TITLE
bug: Remote devices in the UI seem to get stuck at "syncing"

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/syncthing-wrapper#9]
This is complete, the UI just doesn't update.

<img width="568" alt="Screen Shot 2022-04-12 at 11 09 30 AM" src="https://user-images.githubusercontent.com/45926711/163006743-c69c57de-e92b-4846-a303-3fb8b8a09205.png">

**Comment by BitcoinMechanic** [comment]
On the other end, it says "Up To Date"
<img width="566" alt="Screen Shot 2022-04-12 at 11 17 02 AM" src="https://user-images.githubusercontent.com/45926711/163007955-cf6ae5f4-c909-4971-beaa-40d64eb11f57.png">

**Comment by Blu-J** [comment]
The root cause I can't fix, especially since this is a 8+ (https://github.com/syncthing/syncthing/issues/664) year old bug with syncthing. But they have a brute for fix, which makes startup for syncthing slower, but oh well
https://docs.syncthing.net/users/syncthing.html#cmdoption-reset-deltas

**Comment by BitcoinMechanic** [comment]
Those people are saying that their files aren't actually synced though, in my case everything is working fine, it's literally just the UI.

**Comment by RudderDuck** [comment]
I had this sometime and refreshing the page was the only thing to do. Maybe that is also the case for you.
